title:            How nice!
description:      Mu-An Chiou. Designer and front-end developer living in London. I am very nice.
url:              http://muan.co
permalink:        pretty
highlighter:      pygments
markdown:         rdiscount
folder:           stuff
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         Europe/London
paginate: 5
links: 
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/pli88
  - name:         Twitter
    url:          http://twitter.com/pli88
#   - name:         Instagram
#     url:          http://instagram.com/muanchiou